# Generated by Django 2.1.1 on 2018-09-24 17:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hunter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('appearance', models.CharField(max_length=40)),
                ('nen_type', models.CharField(max_length=20)),
                ('background', models.TextField(blank=True)),
            ],
        ),
    ]
